### ISSUE TITLE
IsMounted deprecated

### ISSUE THREAD

**Issue by nebtrx** [valerybugakov/react-selectable-fast#11]
Hi, 
First, congratulations on the job done with this. I've using it for a couple of days and it works like charm, but I'm getting the following warning:

```
Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the SelectableGroup component.
```
According to [this](https://facebook.github.io/react/blog/2015/12/16/ismounted-antipattern.html) `isMounted` is deprecated and will probably be removed in later versions of React. Is there a chance to upgrade this `approach`?

**Comment by valerybugakov** [comment]
Hi, thank you for your feedback!
Can you provide some details on how to reproduce this warning? I haven't seen it in my use cases.

**Comment by nebtrx** [comment]
Sure!. My bad. Sorry for that.

I'm using [`purescript`](http://www.purescript.org/) with [`Pux`](http://www.alexmingoia.com/purescript-pux/) wrapper. My `jsx` view is loaded as a foreign import. `Pux` uses an approach in wich you define a `State` object and `actions`. Every action has an associated transformation that accepts and state as input and returns a new one modified. 

So, I have a matrix of div or buttons which act as `selectables`, those elements rendered from an array contained in the `state`. On my `handleSelectionFinish` handler I gather wich ones are selected and I call one of the actions(defined in my `purescript` code) which update the `state` object(specifically the selected elements ) and performs a `setState`, according to `Pux` underlying implementation, that forces a re-rendering.

These are the react related dependencies I'm using:

```
...
    "react": "^15.0.0",
    "react-ace": "^3.5.0",
    "react-bootstrap": "^0.29.5",
    "react-date-picker": "^5.3.28",
    "react-dom": "^15.0.0",
    "react-dropzone": "^3.5.3",
    "react-fontawesome": "^1.1.0",
    "react-router": "^2.5.2",
    "react-router-bootstrap": "^0.23.0",
    "react-s-alert": "^1.1.4",
    "react-selectable-fast": "^1.2.0",
    "react-tagsinput": "^3.9.1",
...
```

Here is a screenshot of the warning.
<img width="729" alt="screen shot 2016-12-02 at 12 29 19" src="https://cloud.githubusercontent.com/assets/1876959/20843874/315adce8-b88b-11e6-8cb8-042595ce486d.png">

Let me know if you need more info. As the code is private, I'd rather prefer to avoid sharing code snippets as much as possible.

**Comment by valerybugakov** [comment]
I've double check the code according to your stack trace. It looks really weird, because I use mentioned above pattern to unsubscribe `selectableItems` from `selectableGroup` in `componentWillUnmount` lifecycle hook.
In your case you might see this warning only because your `selectableGroup` component is unmounted between `mouseDown` event and `mouseUp` event. I will add some code to cover this case this evening, so you can try it out. 
Also let me know your thoughts about that, maybe I'm thinking in wrong direction here.

**Comment by valerybugakov** [comment]
@nebtrx I've push small fix into master branch, so you can try it out on your code.

**Comment by nebtrx** [comment]
Great @valerybugakov . Sorry for not answering on time. I've been occupied all day with other stuff. I'll check this ASAP(hopefully tonight). Thanks for the commitment taking the time to deal with this pal. Be sure I'll check it out and get back to you

**Comment by andreasloskan** [comment]
```
unregisterSelectable = selectableItem => {
//return false
     this.registry.delete(selectableItem);
  }
```

to:

```
unregisterSelectable = selectableItem => {
    this.registry.forEach(item => {
      if (item.props.selectableKey === selectableItem) {
//return true
        this.registry.delete(item);
      }
    });
  }
```

**Comment by valerybugakov** [comment]
@andreasloskan 
Thanks for your comment, I found an issue in `CreateSelectable` component, `selectableKey` isn't used anymore. Pushed a small fix, let me know if the issue is gone.

**Comment by valerybugakov** [comment]
I will close this one due to inactivity. Feel free to reopen if the issue is still persists.
