### ISSUE TITLE
Max select?

### ISSUE THREAD

**Issue by bkrall** [valerybugakov/react-selectable-fast#12]
This looks great - is there a way to limit how many selections can be made (max select)?

i.e., if I were to list 10 items and only allow up to 5 to be selected.

**Comment by valerybugakov** [comment]
Hey @bkrall for now the only solution I see is to update `ignoreList` prop on the `SelectableGroup` when number of selected items goes off limit. It should do the trick.

Maybe it would be better to implement something like `shouldComponentBeSelected` callback in the package itself which would be called right before selection. What do you think?

**Comment by valerybugakov** [comment]
I will close this one due to inactivity. Feel free to reopen if the issue is still persists.

**Comment by JakeAngell** [comment]
Commenting here as I'd like a similar feature. 

The `shouldComponentBeSelected` callback sounds like an ok idea but I my use case is slightly different. I'd only like to limit the number of selections when the user is clicking. When the user is dragging, there should be no limit on selected items. 

Effectively I want to set a maxSelectedByClick property to 1. So when I click on item A, it becomes selected, if I then click on item B, I've reached my limit of 1, so A should become deselected and B would become selected. 

I can't think of an easy way to achieve this with the current implementation, unless I'm missing something.
