### ISSUE TITLE
Error when importing

### ISSUE THREAD

**Issue by chemitaxis** [valerybugakov/react-selectable-fast#17]
Hi, I have created a new CRA app. I have installed the library with npm:

`npm i -S react-selectable-fast`

After this, I have imported it:

```
import React, { Component } from 'react';
import logo from './logo.svg';
import { SelectableGroup } from 'react-selectable-fast';

import './App.css';

class App extends Component {
  render() {
    return (
      <div className="App">
        <div className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h2>Welcome to React</h2>
        </div>
        <p className="App-intro">
          To get started, edit <code>src/App.js</code> and save to reload.
        </p>
      </div>
    );
  }
}

export default App;
```

But the app, is crashing...

> Failed to compile
> ./node_modules/react-selectable-fast/lib/Selectable-group.js
> Module not found: Can't resolve 'core-js/fn/array/is-array' in '/Users/chemaroldan/code/test_selectable/node_modules/react-selectable-fast/lib'
> This error occurred during the build time and cannot be dismissed.

Any ideas? Thanks!

**Comment by valerybugakov** [comment]
@chemitaxis thanks for the report, it's probably because those polyfills are not added into deps in `package.json`. I will be able to look into it tomorrow, but PR is welcome :) Should be an easy fix though.

https://github.com/valerybugakov/react-selectable-fast/blob/b5a8f88d8f59fd692311d8fd5929c75466cb8b24/src/Selectable-group.js#L1-L5

**Comment by chemitaxis** [comment]
No problem, I can do it ;) I will check at home! Thanks for the work!

**Comment by valerybugakov** [comment]
@chemitaxis hey, thanks for PR! I thought about it one more time and it seems that it's better to exclude those polyfills out of the package and allow users to include them if needed. I've updated README and added a guard check in case of required global are not available. Also I've published an updated version to NPM.

Let me know it works for you :)

**Comment by chemitaxis** [comment]
Hi @valerybugakov is ok for me... thanks! I will close the issue and the PR.
