### ISSUE TITLE
document.body.scrollTop is not computed correctly in the latest Chrome

### ISSUE THREAD

**Issue by Gaara526** [valerybugakov/react-selectable-fast#24]
hi, in the src/getBoundsForNode.js file 'document.body.scrollTop' is aways computed as 0 in the latest Chrome(version61.0.3163.100), but in other version, 'document.body.scrollTop' is computed correctly, so you should do compatible processing，like this 'scrollTop=document.body.scrollTop+document.documentElement.scrollTop'

**Comment by valerybugakov** [comment]
Thanks for reporting that! Should be fixed with a new version in NPM. Please reopen if issue still exists.
