### ISSUE TITLE
Error Uncaught TypeError: this.updater.enqueueCallback is not a function when trying selectbox

### ISSUE THREAD

**Issue by ionHive** [valerybugakov/react-selectable-fast#25]
package.json
{
  "name": "viewcreator",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "babel-eslint": "^7.2.3",
    "babel-polyfill": "^6.26.0",
    "bootstrap": "^3.3.7",
    "d3": "^4.0.0",
    "eslint": "^4.9.0",
    "eslint-plugin-flowtype": "^2.39.1",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.4.0",
    "react": "^16.0.0",
    "react-bootstrap": "^0.31.2",
    "react-dom": "^16.0.0",
    "react-scripts": "^1.0.11",
    "react-selectable-fast": "^2.0.5",
    "webpack": "^3.8.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}

Able to display the page with selectable elements.
Clicking on + selects the item. Clicking on 'Select All' selects all items. Clicking on 'Clear Selection' clears all. the number of items selected is updated.

When using mouse drag to select, the dots of the drag appear and then the following error is thrown. Nothing is selected.
```

Uncaught TypeError: this.updater.enqueueCallback is not a function
    at Selectbox../node_modules/react/lib/ReactBaseClasses.js.ReactComponent.setState (ReactBaseClasses.js:64)
    at HTMLDocument.SelectableGroup._this.openSelectbox (SelectableGroup.js:160)
./node_modules/react/lib/ReactBaseClasses.js.ReactComponent.setState @ ReactBaseClasses.js:64
SelectableGroup._this.openSelectbox @ SelectableGroup.js:160

```
I did npm prune and got a list of peer dependencies. I added them all.

**Comment by valerybugakov** [comment]
@ionHive how can I reproduce this issue in the example? Also it looks like a React related issue: https://github.com/facebook/react/issues/10320

**Comment by valerybugakov** [comment]
@ionHive I got everything working in a scaffolded CRA with your package.json file.

**Comment by ionHive** [comment]
Thanks! I removed all npm modules and re-added them one by one. Then it worked.
