### ISSUE TITLE
How to use this library with inline multiline elements?

### ISSUE THREAD

**Issue by danilvalov** [valerybugakov/react-selectable-fast#28]
Hi.

I have a very interesting case for your brains :)

I have a problem with getting the start and end positions of inline elements in this library. When we try to get a position of a multiline inline element, JS considers the inline element as a block element: start is at the start of the first line (not at the start of the element) and end is at the end of the last line (not at the end of the element).

Correct inline multiline element positions:

```
     ---
---
```

JS considers (incorrect element positions):

```
--------
--------
```

And I don't know how to fix it. Really. No one idea.

Elements example: https://jsfiddle.net/x0q6gsub/

P.S. I hate our designers!!!

**Comment by valerybugakov** [comment]
Hey, so the problem is that you don't want selection to work when lasso is over down right corner of the block because there're no inline elements?
```
--------
----===
```

- lasso activates here
= lasso ignores this area

If not please provide an example with this library :)

**Comment by danilvalov** [comment]
@valerybugakov Yeap, you're right.
I want selection to work only when we see an inline element but not when the inline element ends in an incorrect DOM tree (who considers the inline element as a block element and calculates its position as a block element).

**Comment by danilvalov** [comment]
I did it!

Look:
![](https://cl.ly/0e1Y3K2m3X3R/Screen%20Recording%202018-03-02%20at%2003.56%20AM.gif)

Solution:
https://github.com/danilvalov/react-selectable-fast/commit/e237bd25294c7372742080dc30d38e4cf9c45bc8

Source (with this working example):
https://github.com/danilvalov/react-selectable-fast/tree/feature/add_support_for_inline_multiline_elements

I think most users (almost all) don't need this functionality. So I didn't send the PR to this repo.
Perhaps later I will format the solution for a particular package. But not now because I want to sleep :)

@valerybugakov Thanks for the library and the clean code. It really helped me with my task and saved a lot of time.
