### ISSUE TITLE
Use react-selectable-fast with Redux?

### ISSUE THREAD

**Issue by leopoldjoy** [valerybugakov/react-selectable-fast#3]
@valerybugakov Is it possible to use `react-selectable-fast` with `redux`?

Here is my code:

    import React, {Component, PropTypes} from 'react';
    import {connect} from 'react-redux';
    import { SelectableGroup, createSelectable } from 'react-selectable-fast';
    import autobind from 'autobind-decorator';

    import SelectablePartition from '../SelectablePartition/SelectablePartition';

    import * as selectorActions from 'redux/modules/selectorActions';

    @connect(
      state => ({selectedKeys: state.selector.selectedKeys,
                 selectingKeys: state.selector.selectingKeys}),
      selectorActions)
    export default
    class SelectableDays extends Component {
      static propTypes = {
        selectedKeys: PropTypes.array,
        selectingKeys: PropTypes.array,
        setSelectedKeys: PropTypes.func,
        setSelectingKeys: PropTypes.func
      };

      @autobind
      handleSelection(selectedKeys) {
        this.props.setSelectedKeys(selectedKeys);
        this.props.setSelectingKeys([]);
      }

      @autobind
      handleSelecting(selectingKeys) {
        this.props.setSelectingKeys(selectingKeys);
      }

      render() {
        const SelectableComponent = createSelectable(SelectablePartition);
        const arr = ['1pm', '2pm', '3pm', '4pm'];
        return (
          <SelectableGroup style={{height: '100%'}}
                           onSelectionFinish={this.handleSelection}
                           duringSelection={this.handleSelecting}
                           globalMouse={Boolean(true)}
                           dontClearSelection>
            <div>
              <div>
                {arr.map((hour, i) => {
                  return (
                    <SelectableComponent key={i}
                                         index={i}
                                         hour={hour} />
                  );
                })}
              </div>
            </div>
          </SelectableGroup>
        );
      }
    }

--

    import React from 'react';

    const SelectablePartition = ({ selected, selecting, hour, index }) => (
      <div>{(selected ? 'selected!' : '')}</div>
    );

    export default SelectablePartition;

And the reducer:

    const SET_SELECTED_KEYS = 'myproject/availabilitySelector/SET_SELECTED_KEYS';
    const SET_SELECTING_KEYS = 'myproject/availabilitySelector/SET_SELECTING_KEYS';

    const initialState = {
      selectedKeys: [],
      selectingKeys: []
    };

    export default function reducer(state = initialState, action = {}) {
      switch (action.type) {
        case SET_SELECTED_KEYS:
          return {
            ...state,
            selectedKeys: action.selectedKeys
          };
        case SET_SELECTING_KEYS:
          return {
            ...state,
            selectingKeys: action.selectingKeys
          };
        default:
          return state;
      }
    }

    export function setSelectedKeys(selectedKeys) {
      return {
        type: SET_SELECTED_KEYS,
        selectedKeys
      };
    }

    export function setSelectingKeys(selectingKeys) {
      return {
        type: SET_SELECTING_KEYS,
        selectingKeys
      };
    }

Currently this doesn't work. I'm not getting any errors, but nothing is selectable. Any ideas how I can get this working with `redux`?

**Comment by leopoldjoy** [comment]
@valerybugakov Nevermind, I realized that `react-selectable-fast` internally stores the state, so there's no need to set it up with the reducer. I got it working. Thanks for your great work!

**Comment by valerybugakov** [comment]
@leopoldjoy yep, you can store selected items in Redux state using callbacks `duringSelection` and `onSelectionFinish`.

**Comment by ivadenis** [comment]
@valerybugakov for redux, it would be much more flexible if you got rid of internal state. That way the component is more flexible IMHO. For example, you can implement sorting/filtering/hot-keys etc. based on the actions outside of SelectableGroup.

**Comment by valerybugakov** [comment]
@ivadenis can you describe a case where internal state of the plugin will limit an ability to implement those features with Redux or any other state management container? From my understanding it can be done easily with HOC over SelectableGroup which will sort/filter element or handle hot keys.
