### ISSUE TITLE
Using this with input fields

### ISSUE THREAD

**Issue by madebysid** [valerybugakov/react-selectable-fast#31]
Hey @valerybugakov!

First off, thanks for this library, it has made my life so much simpler! I'm currently using this with `input` elements. What I see is that if the input element is inside the `SelectableGroup`, clicking on the input is treated as a click on the selectable item, and it isn't propagated inside the element. As a result, I cannot focus the `input`. Here's a little GIF that illustrates this:

![kapture 2018-03-23 at 15 22 53](https://user-images.githubusercontent.com/7689783/37822988-252e5a0e-2eae-11e8-8358-3745ac52827f.gif)

Do note that the entire row is a selectable item, and I have multiple input boxes inside it. I have the `resetOnStart` prop set, and clicking on an input fires the `onSelectionClear` prop of `SelectableGroup`. I'd be happy to provide any more info, should you need it.

I found that events are stopped when a selectable element is clicked:
https://github.com/valerybugakov/react-selectable-fast/blob/master/src/SelectableGroup.js#L420

Is it possible to put this `e.preventDefault()` behind a prop flag? I did try this out, and it solved my issue. I'd be happy to send a pull request if you agree this should be done.
I'd rather not put `input` in the `ignoreList` prop because then I have to start selection from outside the input.

If I'm completely missing something, do let me know! Thanks!

**Comment by valerybugakov** [comment]
Hey @madebysid, is it still a relevant issue for you? If I understand your logic correctly and `e.preventDefault` would be in place then clicking on different inputs inside of the row would select/deselect it every time. Am I missing something here or it's the desired behavior?

**Comment by valerybugakov** [comment]
I'll close this one for now, feel free to reopen.

**Comment by madebysid** [comment]
Hey @valerybugakov, sorry for the delay. The selection/deselection works as expected, but what I'm looking to do is to focus the input so I can type into it. All the columns in the row in the GIF are input fields, but when I try to focus a field there, the library captures the event, selects the row, and then stops propagation, preventing the event from reaching the input. This is what I want to avoid. Thanks for any inputs!

**Comment by heri16** [comment]
This project seems dead. It's suggested we make a fork.
