### ISSUE TITLE
Using react-selectable-fast with a virtualized list

### ISSUE THREAD

**Issue by Felix-N** [valerybugakov/react-selectable-fast#32]
Hi,

I'm using react-selectable-fast together with a virtualized list (using [react-virtualized](https://github.com/bvaughn/react-virtualized)

I'm preserving the selected state outside in the list, and pass it to the elements as prop when they get added to the DOM again.

In case selectable elements are removed and readed to the DOM with the prop/sate selected, the used sets registry and selectedItems will add a new item without removing the old one.

I've added a fix for my case, testing if the key of the selected element is already in the set present while the element is not in the set and in that case delete the set element with the given key.

However thats currently specific to my data layout, perhaps someone has an idea how to solve this suitable for more cases.

**Comment by valerybugakov** [comment]
Hey @Felix-N, thanks for pointing to the issue! 

There's an `unregister` call in `componentWillUnmount` method of the `selectable` item. But in the implementation of this method I don't remove this item from `selectedItems` and `selectingItems` registries.

Will release fixed version today which should solve the issue for you.

**Comment by valerybugakov** [comment]
I'll close this one for now, feel free to reopen.
