### ISSUE TITLE
Selection should sustain if we reposition the items

### ISSUE THREAD

**Issue by danial24** [valerybugakov/react-selectable-fast#34]
Let say I have 10 items in the list. I have selected an item that is at the 5th position. Now I do a reorder of the list or a sort. Now that Item that was selected has now moved to a new position let say 8th. 
Expected:
It should be selected there.
Actual:
It is not selected
And the Item that is now on  5th position is selected.

Please correct me if there is some issue with the usage of the library.

**Comment by danial24** [comment]
I am reordering a list with some of the items pre selected.
Let say I have two Items => Item1 and Item2
Item1 is selected
Item2 is not

When I reverse the list, item1 is now replaced with item2
Expected:
Item1 should be selected
Actual: 
Item2 is selected

I guess the selected position remains selected whatever item is rendered.

**Comment by valerybugakov** [comment]
@danial24 have you checked the example app? It works there as expected.

**Comment by valerybugakov** [comment]
I'll close it, for now, feel free to reopen if the issue still exists.
