### ISSUE TITLE
Drag select box is out of position when using flex styling

### ISSUE THREAD

**Issue by tgreen7** [valerybugakov/react-selectable-fast#39]
demo of issue: https://tgreen7.github.io/test-react-selectable/
repo of issue: https://github.com/tgreen7/test-react-selectable

**Comment by valerybugakov** [comment]
Yeah, it seems that `flex-box` styling doesn't allow selectox to receive right X and Y coordinates. Do you have any thoughts on how to fix it?

**Comment by Studio384** [comment]
I am running into the same issue, do you happen to have a fix for this?

**Comment by valerybugakov** [comment]
@Studio384 I'm not actively using the library at the moment. PRs welcome! 😊

**Comment by b-mahjour** [comment]
The way I fixed this was by removing any elements above the selectable container within the flex-box, and hard coded (position: absolute; top:0; left:0) those elements outside of the flex-box. Then hard code the location of the flex-box (position: absolute; bottom:0; width:100%). You may have to play around with it a little but it should work.

**Comment by valerybugakov** [comment]
`position: relative;` is added as a default style for the `SelectableGroup` because it's required for the correct positioning of the `SelectBox` component. It should solve the issue.
