### ISSUE TITLE
Not working on mobile

### ISSUE THREAD

**Issue by leopoldjoy** [valerybugakov/react-selectable-fast#4]
I setup and installed react-selectable-fast. However when I view the app on iOS devices, touch/drag selection doesn't work, only tap. So it is not possible to select multiple items with one motion.

**Comment by valerybugakov** [comment]
It's a known, I'm planning to fix that. But I will be happy to accept a pull request with this functionality.

**Comment by leopoldjoy** [comment]
@valerybugakov Please see my [pull request](https://github.com/valerybugakov/react-selectable-fast/pull/6), I have added mobile support for drag.
