### ISSUE TITLE
Deselect on onSelectionFinish

### ISSUE THREAD

**Issue by Studio384** [valerybugakov/react-selectable-fast#40]
My usecase is as follows: Users can select an number of cells in an table to mark that at that point in time a certain thing has to happen. They can do this with multiple colors and thus the `onSelectionFinished`-event always writes the selected fields away to an array which on its turn render the visual field with the different colors. However, the selected boxes remain "selected". How can I deselect a selection automatically at the end of `onSelectionFinished`?

**Comment by vickyvishal** [comment]
Hi, How were you able to fix this?

**Comment by Studio384** [comment]
I ddin't. I instead opted to make the selected state look like it isn't selected at all. That was the initial solution, but afterwards we built an internal replacement for this that did do the job.

**Comment by vickyvishal** [comment]
It seems like there should be a way to do this, but can't find it in the documentation. Ergo opening this issue
