### ISSUE TITLE
Horizontal scrolling container

### ISSUE THREAD

**Issue by harry-sm** [valerybugakov/react-selectable-fast#42]
If the container has vertical scrolling the selection works great, however, if its horizontal the selection won't scroll horizontally.

Is there a workaround?

**Comment by valerybugakov** [comment]
@harry-sm it's not implemented in this package. It should be quite easy to add this functionality using the existing codebase, I would be happy to merge such a PR.

**Comment by valerybugakov** [comment]
Horizontal scrolling is released in the latest version `v3.0.0`.
