### ISSUE TITLE
Only use mouse button 0 (left for right handed, right for left handed mice).

### ISSUE THREAD

**Issue by miklschmidt** [valerybugakov/react-selectable-fast#44]
This would be a good idea in general IMO. In my specific use case, i need context menu's on selections which are accessed with the button 2. As it is right now, that causes a new select box, which, with `resetOnStart = true` clears the selection. Kind of unfortunate :)

**Comment by valerybugakov** [comment]
@miklschmidt good catch, I've updated the library to start selection on left button press only for now. Main button  doesn't work for me using track pad and latest chrome on Mac OS. Let me know it solves the issue for you.
