### ISSUE TITLE
WhiteList not working on drag

### ISSUE THREAD

**Issue by leopoldjoy** [valerybugakov/react-selectable-fast#5]
WhiteList is not working on drag—if you drag a box that includes a whitelisted item, it is selected. *Only* clicking is disabled for whitelisted items.

**Comment by leopoldjoy** [comment]
@valerybugakov Please note, my new [pull request](https://github.com/valerybugakov/react-selectable-fast/pull/6) fixes this issue.

**Comment by valerybugakov** [comment]
@leopoldjoy I've published new version to NPM. Thanks for your contributions!
