### ISSUE TITLE
Support for Ctrl and Shift key

### ISSUE THREAD

**Issue by camdarley** [valerybugakov/react-selectable-fast#53]
I'm trying to get similar behavior to a file browser.
Here is what I'm looking for:
Clicking on a selectable item select this item and deselect all other selected items, so only one item is selected at a time.
If the Ctrl key is pressed while clicking on an element, this element is added to the selection, if said item is already selected, it is removed from the selection.
If the Shift key is pressed while clicking on an element, all the elements between the last element selected and said element are added to the selection.
I think this would be a great feature to add to this module.
Best regards

**Comment by valerybugakov** [comment]
Hey, this behavior is not implemented, so PR is welcome 🤗
