### ISSUE TITLE
Drag select is not working on mobile

### ISSUE THREAD

**Issue by Spydy** [valerybugakov/react-selectable-fast#54]
Selecting multiple items with drag select doesn't seem to be working correctly on mobile. 

For some reason, it works flawlessly in the demo running in http://valerybugakov.github.io/react-selectable-fast/

But when I run the demo locally it just moves the demo window around and doesn't select anything.

How to replicate:

Go to Chrome developer mode (F12) and use responsive mobile view with touch input enabled, first check the demo running on github, the drag selection should work there. 

Then pull the repo, run npm run watch:example and go to your localhost, try drag selecting the items, it just moves the window around without selecting anything.

**Comment by valerybugakov** [comment]
Hey @Spydy, thanks for the report. I've upgraded codebase to Typescript and fixed the issue with mobile scrolling in the same update. It should be available in the new package version `v3.0.0`. Let me know if the problem still exists.
