### ISSUE TITLE
Modifier keys

### ISSUE THREAD

**Issue by bredikhin** [valerybugakov/react-selectable-fast#58]
Thanks for creating and maintaining this package, your work is highly appreciated.

Quick question though: is there any specific reason to block selection when any of the modifier keys is pressed?

https://github.com/valerybugakov/react-selectable-fast/blob/883b07e19d536aee3db8d870e5334a79ea7926e2/src/utils/detectMouseButton.ts#L10

Is it made on purpose or there simply was not enough time to handle those cases?

**Comment by Krknv** [comment]
Good question 👍

**Comment by valerybugakov** [comment]
Resolve in https://github.com/valerybugakov/react-selectable-fast/pull/69
Thanks @Krknv
