### ISSUE TITLE
onSelectionFinish keeps firing on when unmounted

### ISSUE THREAD

**Issue by Studio384** [valerybugakov/react-selectable-fast#60]
Since version 3, when the component that has the SelectableGroup in it unmounts, the onSelectionFinish-event keeps firing (sometimes up to 600+ times).

**Comment by snsheth55** [comment]
Hey did you figure out a solution to this issue, I am getting a similar error when the component unmounts: 

Uncaught TypeError: Cannot read property 'handleSelectionFinish' of null
    at App123.handleSelectionFinish (TestArea5.js:51)
    at Object.SelectableGroup._this.unregisterSelectable [as unregister] (SelectableGroup.js:187)
    at SelectableItem.componentWillUnmount (CreateSelectable.js:101)

**Comment by Studio384** [comment]
https://github.com/valerybugakov/react-selectable-fast/blob/master/src/SelectableGroup.tsx#L204

This seems to be the offending line. I'm not sure why this behavior would ever be required. Regardless, this illustrates the need for a proper changelog, it wasn't there in 2.3.1.

**Comment by valerybugakov** [comment]
@snsheth55 `handleSelectionFinish` sounds like another issue, could you create example with the issue on codesandbox?

**Comment by valerybugakov** [comment]
@Studio384 the idea of an additional `onSelectionFinish`  call is to notify user that some selected component did unmount and probably should be deleted from the list of the `selectedItems`. It's a good idea not to call this method if unmounted item is not selected yet to avoid redundant `onSelectionFinish` calls. 

Does it sound reasonable?

**Comment by seeden** [comment]
I have same issue. I am showing loading after onSelectionFinish and unmount whole component. It will call onSelectionFinish multiple times with bad values.

**Comment by romecode** [comment]
Seeing the same issue. I have the selection mounted in a tab kind of behavior and when switching tabs onSelectionFinish fn fires with an empty value. Looks like mine fires 3 times.
