### ISSUE TITLE
React selectable in table format?

### ISSUE THREAD

**Issue by snsheth55** [valerybugakov/react-selectable-fast#62]
I want to use react selectable for an admin to select times when a user can login, so I want to put it in table when the y axis is days and x axis is hours 0-24, I wanted to know if and how it would be possible with react selectable? Thanks for the help!

**Comment by valerybugakov** [comment]
The best way to start with it is to look into [example app from this repo](https://github.com/valerybugakov/react-selectable-fast/tree/master/example/src). 
To accomplish that `Table` component should be wrapped into a `SelectableGroup` and each `Cell` component into `createSelectable`.
