### ISSUE TITLE
Feature Request: Add onSelectionStart method

### ISSUE THREAD

**Issue by andre-araujo** [valerybugakov/react-selectable-fast#64]
## Feature proposal

`onSelectionStart` prop that is fired before selectable bounding boxes are calculated.

## Expected behaviour

Change the sizes of the selectable at the moment that the selection starts.

## Current behaviour

If you what to change the size of the selectable at the moment that you start selecting a wrong bounding box are going to be used to calculate the overlapping.

I can work on this feature if it makes sense, currently, I had to make a work-around to achieve the desired result.

**Comment by valerybugakov** [comment]
Sounds reasonable, shoot PR with this feature 👍
