### ISSUE TITLE
Merging in the disable-select-start PR

### ISSUE THREAD

**Issue by edsztukowski** [valerybugakov/react-selectable-fast#87]
Would you be willing to take a look at this PR soon? This library is really amazing, but this is the only thing causing issues for me at the moment. I'm integrating this with ReactDnD and need to be able to drag elements in addition to them being set as "selected" without the marquee.

_Originally posted by @floifyed in https://github.com/valerybugakov/react-selectable-fast/pull/81#issuecomment-636197583_

**Comment by Jwrighty** [comment]
Have just switched over from react-selectable due to some of the performance issues and have this exact use case as well. Would be great to see this worked in

**Comment by edsztukowski** [comment]
For what it's worth @Jwrighty, I sort of have a work around for this. In a parent component that contains `<SelectableGroup>` I have this state:

`const [ disableSelection, setDisableSelection ] = useState(false)`

I pass down `setDisableSelection` to the children of `<SelectableGroup>` and am triggering it with `onMouseEnter` and `onMouseLeave` 

`<div ref={props.selectableRef} onMouseEnter={(e) => props.setDisableSelection(true)} onMouseLeave={(e) => props.setDisableSelection(false)}>`

The problem with this is that I also had to add an onClick event to this div to basically fake a selection on click, since it's disabling the ability to select.

**Comment by Jwrighty** [comment]
Thanks @edsztukowski this works perfectly, am already managing click selection state separately. Appreciate you looping back in on this
