### ISSUE TITLE
Allow disabling support for selection box

### ISSUE THREAD

**Issue by Maher4Ever** [valerybugakov/react-selectable-fast#9]
Hey there,

I'm wrapping a [Material-UI](http://www.material-ui.com/) list with a `SelectableGroup` to allow users to multi-select them. I only want users to be able to click on items to select them and deselect them. However, if a user moves his mouse slightly while clicking it's registered as a mouse up event and if the item it already selected nothing happens! 

Would it be possible to add an option to only allow selection via clicks (i.e., disable selection box)?

PS: Thank you for creating this component! It's awesome!

**Comment by Maher4Ever** [comment]
Another option ofc is to allow deselecting items using the selection box.

**Comment by valerybugakov** [comment]
Hey @Maher4Ever 
It's a good call, I've pushed some changes - check out `enableDeselect` and `mixedDeselect` options in README.md. Also can you test on your end that everything ok and then I'll publish an updated version to the NPM?

**Comment by Maher4Ever** [comment]
Thank you very much for the quick change! It works flawlessly :). 

Note: The example code and the usage section in README still reference the `dontClearSelection` prop that got removed.

**Comment by valerybugakov** [comment]
Thanks, published new version to NPM, check it out 😊

**Comment by Maher4Ever** [comment]
Perfect! Thank you again.
